# Generated by Django 5.0.6 on 2024-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀 이름')),
                ('description', models.TextField(blank=True, null=True, verbose_name='팀 설명')),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team_image/', verbose_name='팀 사진')),
            ],
        ),
    ]
