# Generated by Django 4.1.12 on 2024-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀 이름')),
                ('description', models.TextField(blank=True, null=True, verbose_name='팀 설명')),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='team_image/', verbose_name='팀 사진')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(related_name='users', to='accounts.team', verbose_name='소속 팀'),
        ),
    ]
