# Generated by Django 5.0.6 on 2024-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team_customuser_teams'),
        ('chat', '0003_alter_room_teams_alter_teamroom_team'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(related_name='users', to='teams.team', verbose_name='소속 팀'),
        ),
    ]
