# Generated by Django 4.1.12 on 2024-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='document_ocr/%Y-%m-%d/')),
                ('result', models.TextField()),
                ('finished_at', models.TimeField()),
                ('is_success', models.BooleanField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_ip', models.CharField(max_length=50)),
                ('requested_user', models.CharField(max_length=50)),
            ],
        ),
    ]
