# Generated by Django 4.1.12 on 2024-04-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_ocr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrrequestlog',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='ocrrequestlog',
            name='is_success',
        ),
    ]
