# Generated by Django 4.1.12 on 2024-05-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_team_customuser_teams'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rooms', to='chat.room')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rooms', to='accounts.team')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='teams',
            field=models.ManyToManyField(related_name='rooms', through='chat.TeamRoom', to='accounts.team', verbose_name='소속 팀'),
        ),
    ]
