# Generated by Django 5.0.6 on 2024-05-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_teamroom_room_teams'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='teams',
            field=models.ManyToManyField(related_name='rooms', through='chat.TeamRoom', to='teams.team', verbose_name='소속 팀'),
        ),
        migrations.AlterField(
            model_name='teamroom',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rooms', to='teams.team'),
        ),
    ]
